version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: visits-redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - visits-network

volumes:
  redis-data:

networks:
  visits-network:
    driver: bridge
